INSERT INTO Users (id, username) VALUES (100, 'test user');

INSERT INTO Message (id, message_text) VALUES (100, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (101, 'This is another message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (102, 'This is the third message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (103, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (104, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (105, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (106, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (107, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (108, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (109, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (110, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (111, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (112, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (113, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (114, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (115, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (116, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (117, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (118, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (119, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (120, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (121, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (122, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (123, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (124, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (125, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (126, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (127, 'This is a message text from data.sql');
INSERT INTO Message (id, message_text) VALUES (128, 'This message is exactly 43 character long!!');

INSERT INTO USERS_MESSAGES (user_id, messages_id) VALUES (100, 100);